sudo: required
language: java
jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login --username $HEROKU_USERNAME --password $HEROKU_AUTH_TOKEN registry.heroku.com
  - docker build -t registry.heroku.com/ncedu-docker-demo/web .
  - >
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then
      docker push registry.heroku.com/ncedu-docker-demo/web;
      heroku container:release web --app $HEROKU_APP_NAME;
    fi;
